# Generated by Django 2.1.3 on 2018-11-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=35)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('rut', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
