# Generated by Django 2.1.3 on 2018-12-07 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(blank=True, max_length=10)),
                ('rut', models.CharField(max_length=13)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9)),
                ('email', models.EmailField(blank=True, default='null', max_length=70)),
                ('telefono', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('universidadProcedencia', models.CharField(max_length=40)),
                ('posee', models.CharField(blank=True, choices=[('Equivalencia', 'Equivalencia'), ('Homologación', 'Homologación'), ('No Aplica', 'No Aplica')], default='null', max_length=30)),
                ('nivelacion', models.CharField(blank=True, choices=[('Necesita', 'Necesita'), ('No necesita', 'No necesita')], default='null', max_length=15)),
                ('resultadosNivelacion', models.CharField(blank=True, choices=[('Aprueba', 'Aprueba'), ('Reprueba', 'Reprueba'), ('No Aplica', 'No Aplica')], default='null', max_length=30)),
                ('semestreIngreso', models.IntegerField(blank=True, default='null')),
                ('anioIngreso', models.IntegerField(blank=True, default='null')),
                ('estadoMatricula', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='null', max_length=9)),
                ('antecedentesAcademicos', models.IntegerField(blank=True, default='null')),
                ('antecedentesProfesionales', models.IntegerField(blank=True, default='null')),
                ('cartaRecomendacion', models.IntegerField(blank=True, default='null')),
                ('entrevista', models.CharField(blank=True, default='null', max_length=30)),
                ('puntaje', models.IntegerField(blank=True, default='null')),
                ('resultadosCondicion', models.CharField(blank=True, choices=[('Aprueba', 'Aprueba'), ('Reprueba', 'Reprueba'), ('No Aplica', 'No Aplica')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=13)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('cursosImpartados', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='static/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
