# Generated by Django 2.1.3 on 2018-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=13)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9)),
                ('telefono', models.SmallIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('cursosImpartados', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestreCursado',
            field=models.CharField(max_length=20),
        ),
    ]
