# Generated by Django 2.1.3 on 2018-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
