# Generated by Django 2.1.3 on 2018-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20181118_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
